# Numpy_Assignment_2::

# MUHAMMAD WAJEEH ARIF


# PIAIC161905

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
import numpy as np
x= np.arange(10)
y = x.reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [31]:
x = np.arange(10).reshape(2,5)

y = np.ones(10,int).reshape(2,5)
c= np.vstack([x,y])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [33]:
x = np.arange(10).reshape(2,5)
y = np.ones(10,int).reshape(2,5)
c= np.hstack([x,y])
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [35]:
x = np.arange(10).reshape(2,5)
print(x)
y = x.flatten()
y

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [36]:
x = np.arange(15).reshape(5,3)
print(x,'\n')
y= x.flatten()
y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [37]:
x = np.arange(15)
print(x,'\n')
y = x.reshape(5,3)
y

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [38]:
x = np.arange(25).reshape(5,5)
print(x)
np.square(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [40]:
h = np.arange(30).reshape(5,6)
print(h)
mean = np.mean(h)
print("Mean of array: ",mean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean of array:  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [41]:
x = np.std(h)
print("Standard Dev of array: ",x)

Standard Dev of array:  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [42]:
median = np.median(h)
print("Median of array: ",median)

Median of array:  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [43]:
h.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [44]:
f = np.arange(16).reshape(4,4)
print(f)
print("sum of diagonal elements is: ",np.trace(f))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum of diagonal elements is:  30


## Question:13

### Find the determinant of the previous array in Q12?

In [45]:
from numpy.linalg import det
D = np.arange(10,26).reshape(4,4)
print(D)
det(D)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


7.099748146989094e-29

## Question:14

### Find the 5th and 95th percentile of an array?

In [48]:
array = np.arange(50)
fifth= np.percentile(array, 5) # return 5th percentile,
print("fiftharray :",fifth)
nintyfive= np.percentile(array, 95) # return 95th percentile,
print("nintyfiftharray :",nintyfive)


fiftharray : 2.45
nintyfiftharray : 46.55


## Question:15

### How to find if a given array has any null values?

In [25]:
import numpy as np 
g = np.arange(10)
print(g)
print((g==0).any())


[0 1 2 3 4 5 6 7 8 9]
True
