# **Assignment For Numpy**

# MUHAMMAD WAJEEH ARIF

# BATCH#35

# PIAIC161905

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector=np.zeros((10))
null_vector


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
rangevalue=np.arange(10,50)
rangevalue

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
rangevalue.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
rangevalue.dtype


dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print('numpy version is ',np.__version__)
np.show_config()

numpy version is  1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Arif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhammad Arif/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Arif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhammad Arif/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Arif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhammad Arif/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Arif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhamma

7. Print the dimension of the array in question 3


In [7]:
rangevalue.ndim

1

8. Create a boolean array with all the True values

In [8]:
rangevalue>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

10. Create a three dimensional array



In [10]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
c=np.arange(50)
reversedarray=c[::-1]
reversedarray

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null_vector=np.zeros((10))
v=null_vector[5]=1
null_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
identitymatrix=np.identity(3)
identitymatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5],dtype=float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr=arr1==arr2
arr.all()


False

17. Extract all odd numbers from arr with values(0-9)

In [17]:
oddnum=np.arange(10)
oddnum[oddnum%2==1]




array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array


In [18]:
oddnum=np.arange(10)
oddnum[oddnum%2==1]=-1
oddnum


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:1,0:2]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
array2d=np.arange(9).reshape(3,3)
arr1d=array2d[0]
arr1d

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
array2d=np.arange(9).reshape(3,3)
v=array2d[1][1]
v

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
array2d=np.arange(9).reshape(3,3)
v=array2d[:2,2:]
v

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
randomarray=np.random.randn(10,10)
print(randomarray)
maxno=randomarray.max()
print("maxno:" ,maxno)
minno=randomarray.min()
print("minno:" ,minno)

[[-1.86203308e-01  9.91226790e-01 -5.97128200e-01  1.08499118e+00
  -1.26321744e+00 -1.33307076e+00  1.55223991e+00 -1.06605186e+00
   2.05653979e-01  8.00019988e-02]
 [-5.21062899e-01 -6.38015129e-01 -2.59244568e-01 -7.23871838e-01
  -1.09090371e+00  7.51180662e-01 -9.11352765e-02  1.13876440e+00
   3.51103305e-01 -1.53483403e+00]
 [ 1.37983173e-02 -2.36127908e+00  1.82032969e+00  8.27594931e-01
   1.03777687e+00  1.51820087e+00 -8.70155594e-01  1.41824808e+00
   2.04647571e-01 -1.04204900e+00]
 [-8.12724249e-01 -3.08303426e-01  1.70651789e-01  7.63440514e-01
   2.94234742e-01  2.01351577e+00 -1.39069328e+00 -6.72139215e-01
  -1.24156836e+00 -1.15388377e-01]
 [ 1.09984954e+00  2.37330656e+00  1.30190247e-03 -1.22608412e+00
   5.16905576e-01 -2.69682097e-01 -1.85745006e-01  5.06243846e-01
   1.18470116e+00  1.25989069e-01]
 [-1.48212588e+00  3.33039843e-02  5.27052203e-01  5.71108540e-01
  -1.01896682e+00  2.17187691e-01  1.21274681e+00  1.59256843e-01
   1.71528644e-01 -1.60756101e+00

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common item between a and ab are ",np.intersect1d(a,b))

Common item between a and ab are  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!="Will"]


array([[ 0.22230063, -0.63034966, -0.09438805,  3.19642297],
       [-0.26229049, -0.11165009, -0.46121833, -0.41740446],
       [-0.01908774,  0.11741183,  0.42045821,  1.79383989],
       [ 1.773408  , -1.21377322, -0.48280829, -0.54708587],
       [ 0.68320147,  1.08264928,  0.79061063,  1.40429304]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
print('Names is:\n',names)
print('\nData is:\n',data)
print('\nValues from data where name are not equal to Will and Joe:\n\n',data[(names != 'Will') & (names !='Joe')])

Names is:
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data is:
 [[-1.8763011  -1.49847109  0.31131544  0.16590396]
 [-1.28121481 -1.3974838   0.13621189  0.99922514]
 [ 1.25221692  1.61737667  0.20185268 -1.73677668]
 [-0.1885853  -0.72698568 -1.72531409 -0.61972759]
 [ 0.05901806 -1.11078452 -0.82130557  0.99255465]
 [ 0.27613478 -0.26849912 -1.24701482  0.64266487]
 [-1.7811141   0.22929106  0.87967563 -1.82515454]]

Values from data where name are not equal to Will and Joe:

 [[-1.8763011  -1.49847109  0.31131544  0.16590396]
 [-0.1885853  -0.72698568 -1.72531409 -0.61972759]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr2d=np.arange(1,16).reshape(5,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
z=np.arange(1,17).reshape(2,2,4)
z.shape

(2, 2, 4)

33. Swap axes of the array you created in Question 32

In [33]:
z=np.arange(1,17).reshape(2,2,4)
np.swapaxes(z,0,1)


array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr=np.arange(10)
print(arr)
print(np.sqrt(arr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
Rand1=np.random.randn(12)
print("Rand1: ",Rand1)
Rand2=np.random.randn(12)
print("Rand2: ",Rand2)
result=np.maximum(Rand1,Rand2)
print("Result: ",result)

Rand1:  [-1.22582172  0.10247379  0.92398261 -0.21418241  1.58536713  0.93764553
  0.62377523  0.69755732  1.21531727  0.24543067 -1.17328071 -0.57075356]
Rand2:  [ 1.5926463  -0.26944081 -1.54043028 -1.02306738  0.31723368 -0.30843035
  1.01293939  1.27376751  0.38177486 -1.18308638  0.46682514 -0.61465711]
Result:  [ 1.5926463   0.10247379  0.92398261 -0.21418241  1.58536713  0.93764553
  1.01293939  1.27376751  1.21531727  0.24543067  0.46682514 -0.57075356]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique=np.unique(np.sort(names))
print("Unique: ",unique)

Unique:  ['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
remove=np.setdiff1d(a,b)
print(remove)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])

sampleArray[:,1:2]=10
print(sampleArray)
 

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))


[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
data = np.random.randn(20)
x=data.cumsum()
x

array([-1.43021524, -0.94279301,  0.49651479,  1.33015492,  0.68472625,
        0.45391265,  0.41049633,  1.69922481,  0.09271969,  0.81306856,
        1.01942836,  1.47280663, -0.36199158, -2.15875207, -1.98720338,
       -1.74300749, -1.59982605, -2.67115632, -1.31292717, -1.83999908])